# Generated by Django 5.2.6 on 2025-11-19 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem da Notícia')),
                ('fotografo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fotógrafo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo Completo')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('curtidas_count', models.PositiveIntegerField(default=0, verbose_name='Total de Curtidas')),
                ('salvamentos_count', models.PositiveIntegerField(default=0, verbose_name='Total de Salvamentos')),
                ('urgente', models.BooleanField(default=False, verbose_name='É Urgente?')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor/Editor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='Echo_app.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manchete', models.CharField(max_length=255, verbose_name='Manchete/Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='Echo_app.noticia', verbose_name='Notícia Relacionada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao', 'lida'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categorias_de_interesse', models.ManyToManyField(blank=True, related_name='perfis_interessados', to='Echo_app.categoria', verbose_name='Categorias de Interesse')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.ManyToManyField(blank=True, related_name='usuarios_que_preferem', to='Echo_app.categoria', verbose_name='Categorias Preferidas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de Usuário',
                'verbose_name_plural': 'Preferências de Usuários',
            },
        ),
        migrations.CreateModel(
            name='HistoricoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.PositiveIntegerField(default=0, verbose_name='Pontuação de Interesse')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='Echo_app.categoria', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_interesse', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Interesse',
                'verbose_name_plural': 'Históricos de Interesse',
                'unique_together': {('usuario', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='InteracaoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CURTIDA', 'Curtida'), ('SALVAMENTO', 'Salvamento')], max_length=10, verbose_name='Tipo de Interação')),
                ('data_interacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Interação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_noticias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='Echo_app.noticia', verbose_name='Notícia')),
            ],
            options={
                'verbose_name': 'Interação de Notícia',
                'verbose_name_plural': 'Interações de Notícias',
                'unique_together': {('usuario', 'noticia', 'tipo')},
            },
        ),
    ]
