# Generated by Django 5.2.7 on 2025-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0003_noticia_notificacao_alter_noticia_urgente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagem',
        ),
        migrations.AddField(
            model_name='noticia',
            name='midia',
            field=models.FileField(blank=True, help_text='Anexe uma imagem ou um vídeo para a notícia.', null=True, upload_to='noticias/midia/%Y/%m/', verbose_name='Mídia (Foto ou Vídeo)'),
        ),
    ]
