# Generated by Django 5.2.7 on 2025-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0004_remove_noticia_imagem_noticia_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='midia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem da Notícia'),
        ),
    ]
