# Generated by Django 5.2.7 on 2025-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0004_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='É Urgente?'),
        ),
    ]
