# Generated by Django 5.2.7 on 2025-11-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echo_app', '0005_noticia_urgente'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fotografo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fotógrafo'),
        ),
    ]
